# We also have dkms in the install script.
PACKAGE_NAME="sc0710"
PACKAGE_VERSION="2026.08.29.2"
BUILT_MODULE_NAME[0]="sc0710"
BUILT_MODULE_LOCATION[0]="build/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/media/pci/"
AUTOINSTALL="yes"
MAKE[0]="bash /usr/lib/sc0710/sc0710-dkms-make.sh $kernelver"
