#!/usr/bin/env python3
"""Generate lib/sc0710-tonemap-luts.h — PQ (ST 2084) → SDR preview LUTs.

Curve: paper-white Reinhard
  L_sdr = min(1, 2·T · Y / (Y + 203))

BGR24 / RGB path uses T=0.58 (paper → ~code 200 sRGB).
YUYV uses a dimmer limited-Y LUT (T=0.45) so 4:2:2 previews are not
over-exposed relative to the luminance-preserving BGR24 path.
"""
from pathlib import Path

M1 = 2610.0 / 16384.0
M2 = 2523.0 / 32.0
C1 = 3424.0 / 4096.0
C2 = 2413.0 / 128.0
C3 = 2392.0 / 128.0
PAPER = 203.0
TARGET_RGB = 0.58
TARGET_YUYV = 0.45


def pq_eotf(N):
	N = max(0.0, min(1.0, N))
	if N == 0.0:
		return 0.0
	Nm = N ** (1.0 / M2)
	num = max(Nm - C1, 0.0)
	den = C2 - C3 * Nm
	return 10000.0 * (num / den) ** (1.0 / M1)


def srgb_oetf(L):
	L = max(0.0, min(1.0, L))
	if L <= 0.0031308:
		return 12.92 * L
	return 1.055 * (L ** (1.0 / 2.4)) - 0.055


def rec709_oetf(L):
	L = max(0.0, min(1.0, L))
	if L < 0.018:
		return 4.5 * L
	return 1.099 * (L ** 0.45) - 0.099


def tonemap_nits(Y, target):
	if Y <= 0.0:
		return 0.0
	return min(1.0, (2.0 * target) * Y / (Y + PAPER))


def clamp_u8(x):
	return int(max(0, min(255, round(x))))


def make_y709(target):
	out = []
	for i in range(256):
		if i < 16:
			out.append(16)
			continue
		N = 1.0 if i > 235 else (i - 16) / 219.0
		lin = tonemap_nits(pq_eotf(N), target)
		out.append(clamp_u8(16 + rec709_oetf(lin) * 219))
	return out


def c_array(name, ctype, vals, per=16):
	lines = [f"static const {ctype} {name}[] = {{"]
	for i in range(0, len(vals), per):
		chunk = vals[i:i + per]
		lines.append("\t" + ", ".join(str(v) for v in chunk) + ",")
	lines.append("};")
	return "\n".join(lines)


def main():
	pq_to_srgb = [
		clamp_u8(srgb_oetf(tonemap_nits(pq_eotf(i / 255.0), TARGET_RGB)) * 255)
		for i in range(256)
	]
	pq_y_to_709 = make_y709(TARGET_RGB)
	pq_y_to_709_yuyv = make_y709(TARGET_YUYV)
	pq_to_nits_q12 = [
		int(round(min(pq_eotf(i / 255.0), 10000.0) * 4096.0)) for i in range(256)
	]
	tm_nits_to_lin_q16 = [
		int(round(tonemap_nits(float(n), TARGET_RGB) * 65535.0)) for n in range(4096)
	]
	lin_q10_to_srgb = [clamp_u8(srgb_oetf(i / 1023.0) * 255) for i in range(1024)]
	lin_q10_to_709lim = [
		clamp_u8(16 + rec709_oetf(i / 1023.0) * 219) for i in range(1024)
	]

	root = Path(__file__).resolve().parents[1]
	out = root / "lib" / "sc0710-tonemap-luts.h"
	text = "\n".join([
		"/* Auto-generated by scripts/gen-tonemap-luts.py — do not edit. */",
		"#ifndef SC0710_TONEMAP_LUTS_H",
		"#define SC0710_TONEMAP_LUTS_H",
		"",
		f"/* PQ (ST 2084) → SDR: paper {PAPER:g} nits. RGB/BGR T={TARGET_RGB}, "
		f"YUYV T={TARGET_YUYV}. */",
		"#define SC0710_TM_PAPER_NITS 203",
		"",
		c_array("sc0710_tm_pq_to_srgb", "u8", pq_to_srgb),
		"",
		c_array("sc0710_tm_pq_y_to_709", "u8", pq_y_to_709),
		"",
		"/* Dimmer limited-Y curve for YUYV preview (avoids 4:2:2 over-expose). */",
		c_array("sc0710_tm_pq_y_to_709_yuyv", "u8", pq_y_to_709_yuyv),
		"",
		c_array("sc0710_tm_pq_to_nits_q12", "u32", pq_to_nits_q12, 8),
		"",
		c_array("sc0710_tm_nits_to_lin_q16", "u16", tm_nits_to_lin_q16, 16),
		"",
		c_array("sc0710_tm_lin_q10_to_srgb", "u8", lin_q10_to_srgb),
		"",
		c_array("sc0710_tm_lin_q10_to_709lim", "u8", lin_q10_to_709lim),
		"",
		"#endif",
		"",
	])
	out.write_text(text)
	print(f"wrote {out} ({out.stat().st_size} bytes)")
	print(f"YUYV paper143→{pq_y_to_709_yuyv[143]} mid128→{pq_y_to_709_yuyv[128]} "
	      f"hot200→{pq_y_to_709_yuyv[200]}")


if __name__ == "__main__":
	main()
